=== FTN-E2-materials/XML-i-Web-Servisi/Vezbe/Termin03/Termin03/Java/1. XMLParsers (SAX, StAX, DOM)/data/xsd/zavrsni_rad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ftn.uns.ac.rs/zavrsni_rad"
    targetNamespace="http://www.ftn.uns.ac.rs/zavrsni_rad" elementFormDefault="qualified">

    <xs:element name="rad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naslovna_strana">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="institucija">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="univerzitet" type="xs:string"/>
                                        <xs:element name="fakultet" type="xs:string"/>
                                        <xs:element minOccurs="0" name="departman" type="xs:string"/>
                                        <xs:element minOccurs="0" name="katedra" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="autor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime" type="xs:string"/>
                                        <xs:element name="prezime" type="xs:string"/>
                                        <xs:element minOccurs="0" name="broj_indeksa"
                                            default="RA 1/2012">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern
                                                  value="[a-zA-Z]{1,2} [0-9]{1,3}\/2[0-9]{3}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" name="tema_rada">
                                <xs:complexType mixed="true">
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="jezik" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element default="OAS" name="nivo_studija">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="OAS"/>
                                        <xs:enumeration value="MAS"/>
                                        <xs:enumeration value="DAS"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sadrzaj" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="stavka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naslov_poglavlja" type="xs:string"/>
                                        <xs:element name="broj_strane">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minExclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="poglavlja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="poglavlje"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute default="Diplomski rad" name="vrsta_rada" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="poglavlje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element maxOccurs="unbounded" ref="pasus"/>
                <xs:element ref="poglavlje" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pasus">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element name="slika" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="natpis" type="xs:string"/>
                            <xs:element name="sadrzaj">
                                <xs:simpleType>
                                    <xs:restriction base="xs:base64Binary"/>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="lista">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="stavka" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute default="neuređena" name="vrsta">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="uređena"/>
                                    <xs:enumeration value="neuređena"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tabela" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element form="qualified" maxOccurs="unbounded" name="red">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="celija"
                                            type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="listing" minOccurs="0">
                    <xs:complexType mixed="true">
                        <xs:attribute default="xml" name="jezik">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="java"/>
                                    <xs:enumeration value="python"/>
                                    <xs:enumeration value="php"/>
                                    <xs:enumeration value="c"/>
                                    <xs:enumeration value="c#"/>
                                    <xs:enumeration value="xml"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FTN-E2-materials/XML-i-Web-Servisi/Vezbe/Termin03/Java/1. XMLParsers (SAX, StAX, DOM)/data/xml/zavrsni_rad.xml
<?xml version="1.0" encoding="UTF-8"?>
<rad xmlns="http://www.ftn.uns.ac.rs/zavrsni_rad"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zavrsni_rad ../xsd/zavrsni_rad.xsd"
    vrsta_rada="Diplomski rad">
    <naslovna_strana>
        <institucija>
            <univerzitet>Univerzitet u Novom Sadu</univerzitet>
            <fakultet>Fakultet tehničkih nauka</fakultet>
            <departman>Računarstvo i automatika</departman>
            <katedra>Katedra za informatiku</katedra>
        </institucija>
        <autor>
            <ime>Petar</ime>
            <prezime>Petrović</prezime>
            <broj_indeksa>RA 1/2012</broj_indeksa>
        </autor>
        <tema_rada jezik="srpski">Implementacija podsistema banke u okviru sistema platnog prometa.</tema_rada>
        <tema_rada jezik="engleski">Implementation of banking subsystem in an electronic payment system.</tema_rada>
        <nivo_studija>OAS</nivo_studija>
    </naslovna_strana>
    <sadrzaj>
        <stavka>
            <naslov_poglavlja>1. UVOD</naslov_poglavlja>
            <broj_strane>1</broj_strane>
        </stavka>
        <stavka>
            <naslov_poglavlja>2. ORGANIZACIJA SISTEMA</naslov_poglavlja>
            <broj_strane>3</broj_strane>
        </stavka>
        <stavka>
            <naslov_poglavlja>2.1 Učesnici sistema i njihove uloge</naslov_poglavlja>
            <broj_strane>4</broj_strane>
        </stavka>
        <stavka>
            <naslov_poglavlja>2.1.1 Platni promet</naslov_poglavlja>
            <broj_strane>4</broj_strane>
        </stavka>
    </sadrzaj>
    <poglavlja>
        <poglavlje>
            <naslov>1. UVOD</naslov>
            <pasus>
                Ovde ide tekst prvog pasusa uvodnog poglavlja i prateća ilustracija (slika 1.).
                <slika>
                    <natpis>Slika 1. Prikaz sistema platnog prometa</natpis>
                    <sadrzaj>
                        d2hpbGUoeG1sci5oYXNOZXh0KCkpIHsNCiAgICAgICAgICAgIGV2ZW50VHlwZSA9IHhtbH
                        IubmV4dCgpOw0KICAgICAgICAgICAgcHJpbnRFdmVudFR5cGUoZXZlbnRUeXBlKTsNCg0K
                        ICAgICAgICAgICAgLy8gdGhlc2UgZnVuY3Rpb25zIHByaW50IHRoZSBpbmZvcm1hdGlvbi
                        ANCiAgICAgICAgICAgIC8vIGFib3V0IHRoZSBwYXJ0aWN1bGFyIGV2ZW50IGJ5IGNhbGxp
                        bmcgDQogICAgICAgICAgICAvLyB0aGUgcmVsZXZhbnQgZnVuY3Rpb24NCiAgICAgICAgIC
                        AgIHByaW50U3RhcnRFbGVtZW50KHhtbHIpOw0KICAgICAgICAgICAgcHJpbnRFbmRFbGVt
                        ZW50KHhtbHIpOw0KICAgICAgICAgICAgcHJpbnRUZXh0KHhtbHIpOw0KICAgICAgICAgIC
                        AgcHJpbnRQSURhdGEoeG1scik7DQogICAgICAgICAgICBwcmludENvbW1lbnQoeG1scik7
                        DQogICAgICAgIH0=
                    </sadrzaj>
                </slika>
            </pasus>
            <pasus>
                Ovde ide tekst drugog pasusa uvodnog poglavlja i uređena lista učesnika sistema.
                <lista vrsta="uređena">
                    <stavka>Učesnik br. 1</stavka>
                    <stavka>Učesnik br. 2</stavka>
                    <stavka>Učesnik br. 3</stavka>
                </lista>
                Još malo teksta koji pojašnjava učesnike sistema.
            </pasus>
            <pasus>
                Sledi detaljniji opis učesnika sistema. Detaljniji opis učesnika sistema. Detaljniji opis učesnika sistema. Detaljniji opis učesnika sistema. Detaljniji opis učesnika sistema. Detaljniji opis učesnika sistema.
            </pasus>
        </poglavlje>
        <poglavlje>
            <naslov>2. ORGANIZACIJA SISTEMA</naslov>
            <pasus>
                Ovde ide tekst prvog pasusa drugog poglavlja, a slede i potpoglavlja.
            </pasus>
            <poglavlje>
                <naslov>2.1 Učesnici sistema i njihove uloge</naslov>
                <pasus>
                    Ovde ide tekst prvog pasusa prvog potpoglavlja u drugom poglavlju.
                </pasus>
                <poglavlje>
                    <naslov>2.1.1 Platni promet</naslov>
                    <pasus>Ovde ide tekst prvog pasusa drugog potpoglavlja. Dosta teksta. Još teksta. I još malo teksta.</pasus>
                    <pasus>
                        Ovde ide tekst drugog pasusa, kao i sledeća tabela.
                        <tabela>
                            <red>
                                <celija>Naslov 1</celija>
                                <celija>Naslov 2</celija>
                                <celija>Naslov 3</celija>
                                <celija>Naslov 4</celija>
                            </red>
                            <red>
                                <celija>Sadržaj 1</celija>
                                <celija>Sadržaj 2</celija>
                                <celija>Sadržaj 3</celija>
                                <celija>Sadržaj 4</celija>
                            </red>
                            <red>
                                <celija>Sadržaj 1</celija>
                                <celija>Sadržaj 2</celija>
                                <celija>Sadržaj 3</celija>
                                <celija>Sadržaj 4</celija>
                            </red>
                        </tabela>
                        Još malo teksta u istom pasusu. Tekst koji najavljuje sliku.
                    </pasus>
                    <pasus>
                        Ovde ide tekst trećeg pasusa, najava za sliku 2.
                        <slika>
                            <natpis>Slika 2. Nalog za plaćanje</natpis>
                            <sadrzaj>
                                WE1MSW5wdXRGYWN0b3J5IGZhY3RvcnkgPSBYTUxJbnB1dEZhY3RvcnkubmV3SW5zdGFuY2
                                UoKTsNCg0KWE1MRXZlbnRSZWFkZXIgZXZlbnRSZWFkZXIgPQ0KICAgIGZhY3RvcnkuY3Jl
                                YXRlWE1MRXZlbnRSZWFkZXIoDQogICAgICAgIG5ldyBGaWxlUmVhZGVyKCJkYXRhXHRlc3
                                QueG1sIikpOw0KDQpYTUxTdHJlYW1SZWFkZXIgc3RyZWFtUmVhZGVyID0NCiAgICBmYWN0
                                b3J5LmNyZWF0ZVhNTFN0cmVhbVJlYWRlcigNCiAgICAgICAgbmV3IEZpbGVSZWFkZXIoIm
                                RhdGFcdGVzdC54bWwiKSk7
                            </sadrzaj>
                        </slika>
                        Ovde ide tekst koji opisuje sliku 2 i objašnjava osnovne elemente naloga za plaćanje..
                    </pasus>
                </poglavlje>
            </poglavlje>
        </poglavlje>
    </poglavlja>
</rad>
