=== FTN-E2-materials/XML-i-Web-Servisi/Vezbe/Termin02/Termin02/Primeri_DTD/zavrsni_rad.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- DTD for a graduate thesis. -->
<!ELEMENT zavrsni_rad (naslovna_strana, sadrzaj?, poglavlje*) >
<!ATTLIST zavrsni_rad 
                vrsta_rada      CDATA "Diplomski rad"
                nivo_studija    (oas | mas | das) "oas"
>
<!ELEMENT naslovna_strana (institucija, autor, tema_rada) >

<!ELEMENT institucija (univerzitet, fakultet, departman?, katedra?) >

<!ELEMENT univerzitet (#PCDATA) >
<!ELEMENT fakultet (#PCDATA) >
<!ELEMENT departman (#PCDATA) >
<!ELEMENT katedra (#PCDATA) >

<!ELEMENT autor (ime, prezime) >
<!ATTLIST autor
                broj_indeksa      CDATA #REQUIRED
>

<!ELEMENT ime (#PCDATA) >
<!ELEMENT prezime (#PCDATA) >

<!ELEMENT tema_rada (#PCDATA) >

<!ELEMENT sadrzaj (stavka+) >

<!ELEMENT stavka (#PCDATA) >
<!ATTLIST stavka
                broj_strane     CDATA   #REQUIRED 
>
                
<!ELEMENT poglavlje (naslov, pasus+, poglavlje*) >
<!ELEMENT naslov (#PCDATA) >
<!ELEMENT pasus (#PCDATA | slika | lista | tabela)* >

<!ELEMENT slika (#PCDATA) >
<!ATTLIST slika
                natpis      CDATA   #IMPLIED
>
                
<!ELEMENT lista (element+) >
<!ATTLIST lista
                vrsta       (neuređena | uređena)   "neuređena"
>
                
<!ELEMENT element (#PCDATA) >

<!ELEMENT tabela (red+) >
<!ELEMENT red (celija+) >
<!ELEMENT celija (#PCDATA) >

=== FTN-E2-materials/XML-i-Web-Servisi/Vezbe/Termin02/Primeri_DTD/zavrsni_rad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zavrsni_rad SYSTEM "zavrsni_rad.dtd">
<zavrsni_rad nivo_studija="mas" vrsta_rada="Master rad">
    <naslovna_strana>
        <institucija>
            <univerzitet>Univerzitet u Novom Sadu</univerzitet>
            <fakultet>Fakultet tehničkih nauka</fakultet>
            <departman>Računarstvo i automatika</departman>
            <katedra>Katedra za informatiku</katedra>
        </institucija>
        <autor broj_indeksa="RA 123/2012">
            <ime>Petar</ime>
            <prezime>Petrović</prezime>
        </autor>
        <tema_rada>Peter's bachelor thesis</tema_rada>
    </naslovna_strana>
    <sadrzaj>
        <stavka broj_strane="1">1. Uvod</stavka>
        <stavka broj_strane="5">2. Prvo poglavlje</stavka>
        <stavka broj_strane="9">3. Zakljucak</stavka>
    </sadrzaj>
    <poglavlje>
        <naslov>Naslov poglavlja</naslov>
        <pasus>
            Ovo je neki tekst.
            <lista vrsta="uređena">
                <element>Prva stavka</element>
                <element>Druga stavka</element>
            </lista>
            Ovo je nastavak teksta.
            <tabela>
                <red>
                    <celija>Naslov 1</celija>
                    <celija>Naslov 2</celija>
                </red>
                <red>
                    <celija>Sadrzaj 1</celija>
                    <celija>Sadrzaj 2</celija>
                </red>
            </tabela>
        </pasus>
    </poglavlje>
    <poglavlje>
        <naslov>Naslov sledeceg poglavlja</naslov>
        <pasus>Sadrzaj poglavlja... </pasus>
    </poglavlje>
</zavrsni_rad>
